### PR TITLE
Some implementations and tests

### PR DESCRIPTION
**Pull request by vinyvicente**

### CODE REVIEW

**Comment by peter279k** [comment]
The Travis CI build is failed due to `Error: Call to member function withStatus() on null`.

This should be fixed.

**Comment by arcostasi** [comment]
> The Travis CI build is failed due to Error: Call to member function withStatus() on null.
> This should be fixed.
Can see @vinyvicente ? I'm working on wiring-start. Thanks

**Comment by vinyvicente** [comment]
Thanks, guys. I'll see.

**Comment by arcostasi** [comment]
> withStatus()

withStatus () comes from Psr\Http\Message\ResponseInterface
Responses are considered immutable;
All methods that might change state MUST be implemented such that they retain the internal state of the current message and return an instance that contains the changed state.

**Pull request merged**
